//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CocktailsDModel", "FK_CocktailsIngredients_Cocktails", "Cocktails", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cocktails.WCF.Cocktail), "CocktailsIngredients", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cocktails.WCF.CocktailsIngredient), true)]
[assembly: EdmRelationshipAttribute("CocktailsDModel", "FK_CocktailsIngredients_Ingredients", "Ingredients", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Cocktails.WCF.Ingredient), "CocktailsIngredients", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Cocktails.WCF.CocktailsIngredient), true)]

#endregion

namespace Cocktails.WCF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CocktailsDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CocktailsDBEntities object using the connection string found in the 'CocktailsDBEntities' section of the application configuration file.
        /// </summary>
        public CocktailsDBEntities() : base("name=CocktailsDBEntities", "CocktailsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CocktailsDBEntities object.
        /// </summary>
        public CocktailsDBEntities(string connectionString) : base(connectionString, "CocktailsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CocktailsDBEntities object.
        /// </summary>
        public CocktailsDBEntities(EntityConnection connection) : base(connection, "CocktailsDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cocktail> Cocktails
        {
            get
            {
                if ((_Cocktails == null))
                {
                    _Cocktails = base.CreateObjectSet<Cocktail>("Cocktails");
                }
                return _Cocktails;
            }
        }
        private ObjectSet<Cocktail> _Cocktails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CocktailsIngredient> CocktailsIngredients
        {
            get
            {
                if ((_CocktailsIngredients == null))
                {
                    _CocktailsIngredients = base.CreateObjectSet<CocktailsIngredient>("CocktailsIngredients");
                }
                return _CocktailsIngredients;
            }
        }
        private ObjectSet<CocktailsIngredient> _CocktailsIngredients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ingredient> Ingredients
        {
            get
            {
                if ((_Ingredients == null))
                {
                    _Ingredients = base.CreateObjectSet<Ingredient>("Ingredients");
                }
                return _Ingredients;
            }
        }
        private ObjectSet<Ingredient> _Ingredients;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cocktails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCocktails(Cocktail cocktail)
        {
            base.AddObject("Cocktails", cocktail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CocktailsIngredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCocktailsIngredients(CocktailsIngredient cocktailsIngredient)
        {
            base.AddObject("CocktailsIngredients", cocktailsIngredient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ingredients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToIngredients(Ingredient ingredient)
        {
            base.AddObject("Ingredients", ingredient);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocktailsDModel", Name="Cocktail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cocktail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cocktail object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="preparation">Initial value of the Preparation property.</param>
        /// <param name="imageURL">Initial value of the ImageURL property.</param>
        public static Cocktail CreateCocktail(global::System.Int32 id, global::System.String name, global::System.String description, global::System.String preparation, global::System.String imageURL)
        {
            Cocktail cocktail = new Cocktail();
            cocktail.ID = id;
            cocktail.Name = name;
            cocktail.Description = description;
            cocktail.Preparation = preparation;
            cocktail.ImageURL = imageURL;
            return cocktail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Preparation
        {
            get
            {
                return _Preparation;
            }
            set
            {
                OnPreparationChanging(value);
                ReportPropertyChanging("Preparation");
                _Preparation = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Preparation");
                OnPreparationChanged();
            }
        }
        private global::System.String _Preparation;
        partial void OnPreparationChanging(global::System.String value);
        partial void OnPreparationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageURL
        {
            get
            {
                return _ImageURL;
            }
            set
            {
                OnImageURLChanging(value);
                ReportPropertyChanging("ImageURL");
                _ImageURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageURL");
                OnImageURLChanged();
            }
        }
        private global::System.String _ImageURL;
        partial void OnImageURLChanging(global::System.String value);
        partial void OnImageURLChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocktailsDModel", "FK_CocktailsIngredients_Cocktails", "CocktailsIngredients")]
        public EntityCollection<CocktailsIngredient> CocktailsIngredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CocktailsIngredient>("CocktailsDModel.FK_CocktailsIngredients_Cocktails", "CocktailsIngredients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CocktailsIngredient>("CocktailsDModel.FK_CocktailsIngredients_Cocktails", "CocktailsIngredients", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocktailsDModel", Name="CocktailsIngredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CocktailsIngredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CocktailsIngredient object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="iDctail">Initial value of the IDctail property.</param>
        /// <param name="nameIngr">Initial value of the NameIngr property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        public static CocktailsIngredient CreateCocktailsIngredient(global::System.Int32 id, global::System.Int32 iDctail, global::System.String nameIngr, global::System.String number)
        {
            CocktailsIngredient cocktailsIngredient = new CocktailsIngredient();
            cocktailsIngredient.ID = id;
            cocktailsIngredient.IDctail = iDctail;
            cocktailsIngredient.NameIngr = nameIngr;
            cocktailsIngredient.Number = number;
            return cocktailsIngredient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IDctail
        {
            get
            {
                return _IDctail;
            }
            set
            {
                OnIDctailChanging(value);
                ReportPropertyChanging("IDctail");
                _IDctail = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDctail");
                OnIDctailChanged();
            }
        }
        private global::System.Int32 _IDctail;
        partial void OnIDctailChanging(global::System.Int32 value);
        partial void OnIDctailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NameIngr
        {
            get
            {
                return _NameIngr;
            }
            set
            {
                OnNameIngrChanging(value);
                ReportPropertyChanging("NameIngr");
                _NameIngr = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NameIngr");
                OnNameIngrChanged();
            }
        }
        private global::System.String _NameIngr;
        partial void OnNameIngrChanging(global::System.String value);
        partial void OnNameIngrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocktailsDModel", "FK_CocktailsIngredients_Cocktails", "Cocktails")]
        public Cocktail Cocktail
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cocktail>("CocktailsDModel.FK_CocktailsIngredients_Cocktails", "Cocktails").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cocktail>("CocktailsDModel.FK_CocktailsIngredients_Cocktails", "Cocktails").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cocktail> CocktailReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cocktail>("CocktailsDModel.FK_CocktailsIngredients_Cocktails", "Cocktails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cocktail>("CocktailsDModel.FK_CocktailsIngredients_Cocktails", "Cocktails", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocktailsDModel", "FK_CocktailsIngredients_Ingredients", "Ingredients")]
        public Ingredient Ingredient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("CocktailsDModel.FK_CocktailsIngredients_Ingredients", "Ingredients").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("CocktailsDModel.FK_CocktailsIngredients_Ingredients", "Ingredients").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ingredient> IngredientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ingredient>("CocktailsDModel.FK_CocktailsIngredients_Ingredients", "Ingredients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ingredient>("CocktailsDModel.FK_CocktailsIngredients_Ingredients", "Ingredients", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CocktailsDModel", Name="Ingredient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ingredient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ingredient object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Ingredient CreateIngredient(global::System.Int32 id, global::System.String name)
        {
            Ingredient ingredient = new Ingredient();
            ingredient.ID = id;
            ingredient.Name = name;
            return ingredient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CocktailsDModel", "FK_CocktailsIngredients_Ingredients", "CocktailsIngredients")]
        public EntityCollection<CocktailsIngredient> CocktailsIngredients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CocktailsIngredient>("CocktailsDModel.FK_CocktailsIngredients_Ingredients", "CocktailsIngredients");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CocktailsIngredient>("CocktailsDModel.FK_CocktailsIngredients_Ingredients", "CocktailsIngredients", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
